service: getEtherPrice

frameworkVersion: ">=1.4.0 <2.0.0"

provider:
  name: aws
  runtime: nodejs6.10
  stage: dev
  region: eu-west-1

functions:
  getEtherPrice:
    handler: index.getEtherPrice
    events:
      - alexaSkill
